version: "2.1"
services:
  server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    hostname: server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=password
      - USER_NAME=user
    volumes:
      - ./server:/config
    ports:
      - "2222:2222"
    restart: unless-stopped

  client-1:
    build:
      context: config
      dockerfile: Dockerfile
    container_name: client-1
    hostname: client-1
    tty: true
    volumes:
      - ./client-1:/home/client
    depends_on:
      - server
