version: "2.1"
services:
  server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    hostname: server.test
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=password
      - USER_NAME=user
    volumes:
      - ./server_opt:/opt
    ports:
      - "2222:2222"
    restart: unless-stopped

  client-1:
    build:
      context: config
      dockerfile: Dockerfile
      args:
        - NAME=client1
    container_name: client-1
    hostname: computer-1
    tty: true
    volumes:
      - ./client1:/home/client1
    depends_on:
      - server

  client-2:
    build:
      context: config
      dockerfile: Dockerfile
      args:
        - NAME=client2
    container_name: client-2
    hostname: computer-2
    tty: true
    volumes:
      - ./client2:/home/client2
    depends_on:
      - server
